# Generated by Django 4.2.4 on 2023-08-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='related_list',
        ),
        migrations.DeleteModel(
            name='ListModel',
        ),
    ]
