# Generated by Django 4.2.4 on 2023-08-26 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='related_lists',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='related_list',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.listmodel'),
            preserve_default=False,
        ),
    ]
