# Generated by Django 4.2.4 on 2023-08-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_taskmodel_related_lists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='related_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.listmodel'),
        ),
    ]
